version: '3.8'

services:
  dingtalk-ai-bot:
    build: .
    image: n8n-on-dingtalk-bot:latest
    container_name: n8n-on-dingtalk-bot
    restart: unless-stopped
    env_file:
      - .env
    
